### ISSUE TITLE
Decide on how a cron job would get sprint ids

### ISSUE THREAD

**Issue by jtowe1** [jtowe1/sprint-report-api#27]
When we create a con job to update the days of each sprint, we need a way to tell the cron job which sprints to update.

**Comment by jtowe1** [comment]
I propose we create a way of registering a sprint into a table, so that the cron job can just pull sprint ids from that table.

**Comment by aikaniel** [comment]
Poking around in the Jira api, it's possible to pull just the active sprint of the selected board.

Perhaps we add a path to the sprint chart service that Adds/updates all active sprints for all (or a selection of) boards?

The cron could then just run something like "updateActiveSprints" and let the system work through them.
We need to determine boards though. Perhaps just all FOR boards, or a specific list of boards?

**Comment by jtowe1** [comment]
> Poking around in the Jira api, it's possible to pull just the active sprint of the selected board.

Ah nice, good catch.  I need to look at the boards at work and all of their sprints, to see how many there actually are.  If there aren't a ton, this approach could work.

**Comment by jtowe1** [comment]
We could also have a query that pulls sprints from our database who's dates contain today, so that we only update sprints that are active that someone has looked at at least once.

**Comment by jtowe1** [comment]
* Subscribe board by id
  * subscribed_boards
    * board_id
* Each hour? get active sprints from jira for all subscribed boards
  * `OurStaticClass::updateSprints()`
  * Call from composer script?
* Call `getSprintChartBySprintId` for each of those active sprints
  * Timeout between sprints?
  * Look at jira rate limits
